on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows:
      - release-please
    types:
      - completed

name: deploy

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ jobs.release-please.steps.release.outputs.release_created }}
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Checkout
        uses: actions/checkout@master

      - name: Cache for go pkg
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Deploy
        run: |
          echo "Deployed!"
